spring:
  application:
    name: batch-example
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?profileSQL=true
    username: postgres
    password: qwer1234
    hikari:
      maximum-pool-size: 200
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

prometheus:
  job:
    name: spring-batch
  pushgateway:
    url: localhost:9091