-- CREATE TABLE BATCH_JOB_INSTANCE
-- (
--     JOB_INSTANCE_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     VERSION         BIGINT,
--     JOB_NAME        VARCHAR(100) NOT NULL,
--     JOB_KEY         VARCHAR(32)  NOT NULL,
--     constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
-- );
--
-- CREATE TABLE BATCH_JOB_EXECUTION
-- (
--     JOB_EXECUTION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     VERSION          BIGINT,
--     JOB_INSTANCE_ID  BIGINT       NOT NULL,
--     CREATE_TIME      TIMESTAMP(9) NOT NULL,
--     START_TIME       TIMESTAMP(9) DEFAULT NULL,
--     END_TIME         TIMESTAMP(9) DEFAULT NULL,
--     STATUS           VARCHAR(10),
--     EXIT_CODE        VARCHAR(2500),
--     EXIT_MESSAGE     VARCHAR(2500),
--     LAST_UPDATED     TIMESTAMP(9),
--     constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
--         references BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
-- );
--
-- CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
-- (
--     JOB_EXECUTION_ID BIGINT       NOT NULL,
--     PARAMETER_NAME   VARCHAR(100) NOT NULL,
--     PARAMETER_TYPE   VARCHAR(100) NOT NULL,
--     PARAMETER_VALUE  VARCHAR(2500),
--     IDENTIFYING      CHAR(1)      NOT NULL,
--     constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
--         references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
-- );
--
-- CREATE TABLE BATCH_STEP_EXECUTION
-- (
--     STEP_EXECUTION_ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     VERSION            BIGINT       NOT NULL,
--     STEP_NAME          VARCHAR(100) NOT NULL,
--     JOB_EXECUTION_ID   BIGINT       NOT NULL,
--     CREATE_TIME        TIMESTAMP(9) NOT NULL,
--     START_TIME         TIMESTAMP(9) DEFAULT NULL,
--     END_TIME           TIMESTAMP(9) DEFAULT NULL,
--     STATUS             VARCHAR(10),
--     COMMIT_COUNT       BIGINT,
--     READ_COUNT         BIGINT,
--     FILTER_COUNT       BIGINT,
--     WRITE_COUNT        BIGINT,
--     READ_SKIP_COUNT    BIGINT,
--     WRITE_SKIP_COUNT   BIGINT,
--     PROCESS_SKIP_COUNT BIGINT,
--     ROLLBACK_COUNT     BIGINT,
--     EXIT_CODE          VARCHAR(2500),
--     EXIT_MESSAGE       VARCHAR(2500),
--     LAST_UPDATED       TIMESTAMP(9),
--     constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
--         references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
-- );
--
-- CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
-- (
--     STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
--     SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
--     SERIALIZED_CONTEXT LONGVARCHAR,
--     constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
--         references BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
-- );
--
-- CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
-- (
--     JOB_EXECUTION_ID   BIGINT        NOT NULL PRIMARY KEY,
--     SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
--     SERIALIZED_CONTEXT LONGVARCHAR,
--     constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
--         references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
-- );
--
-- CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ;
-- CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ;
-- CREATE SEQUENCE BATCH_JOB_SEQ;

create table products
(
    product_id       varchar(250) primary key,
    seller_id        bigint       not null,
    category         varchar(255) not null,
    product_name     varchar(255) not null,
    sales_start_date date,
    sales_end_date   date,
    product_status   varchar(50),
    brand            varchar(255),
    manufacturer     varchar(255),
    sales_price      integer      not null,
    stock_quantity   integer      not null default 0,
    created_at       timestamp             default current_timestamp,
    updated_at       timestamp             default current_timestamp
);

create index idx_products_status on products (product_status);
create index idx_products_category on products (category);
create index idx_products_brand on products (brand);
create index idx_products_manufacturer on products (manufacturer);
create index idx_products_seller_id on products (seller_id);